DROP TABLE IF EXISTS USUARIO_USR;
CREATE TABLE USUARIO_USR (
  USR_ID CHAR(32) NOT NULL,
  USR_LOGIN char(8) DEFAULT NULL,
  USR_ACTIVO char(1) DEFAULT NULL,
  USR_PASSWORD char(50) DEFAULT NULL,
  USR_NOMBRE char(50) DEFAULT NULL,
  USR_APELLIDO1 char(50) DEFAULT NULL,
  USR_APELLIDO2 char(50) DEFAULT NULL,
  USR_COUNTRY char(2) DEFAULT NULL,
  USR_LANG char(2) DEFAULT NULL,
  USR_VARIANT char(25) DEFAULT NULL
);
CREATE UNIQUE INDEX USUARIO_USR_KEY ON USUARIO_USR(USR_ID);
CREATE UNIQUE INDEX USUARIO_USR_INX_LOGIN ON USUARIO_USR(USR_LOGIN);
CREATE INDEX USUARIO_USR_INX_ACTIVO ON USUARIO_USR(USR_ACTIVO,USR_LOGIN);

DROP TABLE IF EXISTS GRUPO_GRP;
CREATE TABLE GRUPO_GRP (
  GRP_ID CHAR(32) NOT NULL,
  GRP_DESC char(255) DEFAULT NULL
);
CREATE UNIQUE INDEX GRUPO_GRP_KEY ON GRUPO_GRP(GRP_ID);

DROP TABLE IF EXISTS ROLE_ROL;
CREATE TABLE ROLE_ROL (
  ROL_ID CHAR(32) NOT NULL,
  ROL_NAME char(20) DEFAULT NULL,
  ROL_DESC char(255) DEFAULT NULL
);
CREATE UNIQUE INDEX ROLE_ROL_KEY ON ROLE_ROL(ROL_ID);
CREATE UNIQUE INDEX ROLE_ROL_INX_ROLENAME ON ROLE_ROL(ROL_NAME);


DROP TABLE IF EXISTS GRP_GRP;
CREATE TABLE GRP_GRP (
  GRP_ID CHAR(32) NOT NULL,
  GRP_ID1 CHAR(32) NOT NULL
);
CREATE UNIQUE INDEX GRP_GRP_KEY ON GRP_GRP(GRP_ID,GRP_ID1);


DROP TABLE IF EXISTS GRP_ROL;
CREATE TABLE GRP_ROL (
  GRP_ID CHAR(32) NOT NULL,
  ROL_ID CHAR(32) NOT NULL
);
CREATE UNIQUE INDEX GRP_ROL_KEY ON GRP_ROL(GRP_ID,ROL_ID);
CREATE INDEX GRP_ROL_INDX_GRP ON GRP_ROL(GRP_ID);


DROP TABLE IF EXISTS USR_GRP;
CREATE TABLE USR_GRP (
  USR_ID CHAR(32) NOT NULL,
  GRP_ID CHAR(32) NOT NULL
);
CREATE UNIQUE INDEX USR_GRP_KEY ON USR_GRP(USR_ID,GRP_ID);
CREATE INDEX USR_GRP_INDX_USR ON USR_GRP(USR_ID);

DROP TABLE IF EXISTS USR_ROL;
CREATE TABLE USR_ROL (
  USR_ID CHAR(32) NOT NULL,
  ROL_ID CHAR(32) NOT NULL
);
CREATE UNIQUE INDEX USR_ROL_KEY ON USR_ROL(USR_ID,ROL_ID);
CREATE INDEX USR_ROL_INDX_USR ON USR_ROL(USR_ID);
