DROP TABLE IF EXISTS DICDESC_DICD;
CREATE TABLE DICDESC_DICD (
  DICD_ID CHAR(32) NOT NULL,
  DICD_DESC text
)
;
CREATE UNIQUE INDEX DICDESC_DICD_KEY ON DICDESC_DICD(DICD_ID);

DROP TABLE IF EXISTS OPERATIVAS_OP;
CREATE TABLE OPERATIVAS_OP (
  OP_GRUPO char(6) NOT NULL,
  DICD_ID CHAR(32),
  OP_DESC varchar(255) DEFAULT NULL
)
;
CREATE UNIQUE INDEX OPERATIVAS_OP_KEY ON OPERATIVAS_OP(OP_GRUPO);

DROP TABLE IF EXISTS DICCIONARIO_DIC;
CREATE TABLE DICCIONARIO_DIC (
  OP_GRUPO char(6) NOT NULL,
  DIC_ID DECIMAL(5) NOT NULL,
  DIC_TIPO DECIMAL(1) DEFAULT NULL,
  DICD_ID CHAR(32),
  DIC_NOMBRE varchar(50) NOT NULL,
  DIC_LONG0 DECIMAL(10) DEFAULT NULL,
  DIC_LONG1 DECIMAL(10) DEFAULT NULL,
  DIC_STR0 varchar(50) DEFAULT NULL,
  DIC_STR1 varchar(50) DEFAULT NULL,
  DIC_STR2 varchar(50) DEFAULT NULL,
  DIC_STR3 varchar(50) DEFAULT NULL,
  DIC_STR4 varchar(50) DEFAULT NULL,
  DIC_STR5 varchar(50) DEFAULT NULL
);
CREATE UNIQUE INDEX DICCIONARIO_DIC_KEY ON DICCIONARIO_DIC(OP_GRUPO,DIC_ID);

DROP TABLE IF EXISTS REGISTRO_REG;
CREATE TABLE REGISTRO_REG (
  OP_GRUPO char(6) NOT NULL DEFAULT '',
  DIC_ID DECIMAL(5) NOT NULL,
  REG_ORDEN DECIMAL(3) NOT NULL,
  OP_GRUPO0 char(6) NOT NULL,
  DIC_ID0 DECIMAL(5) NOT NULL,
  REG_OBLIGATORIO DECIMAL(1) DEFAULT NULL,
  REG_INT0 DECIMAL(3) DEFAULT NULL,
  REG_INT1 DECIMAL(3) DEFAULT NULL
)
;
CREATE UNIQUE INDEX REGISTRO_REG_KEY ON REGISTRO_REG(OP_GRUPO,DIC_ID,REG_ORDEN);

DROP TABLE IF EXISTS SERVICIO_SVRD;
CREATE TABLE SERVICIO_SVRD (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID DECIMAL(3) NOT NULL,
  SVR_VERSION DECIMAL(2) DEFAULT NULL,
  DICD_ID CHAR(32),
  SVR_INHERIT DECIMAL(1) DEFAULT 1,
  SVR_PUBLIC DECIMAL(1) DEFAULT 1,
  SVRD_DESC varchar(255) DEFAULT NULL
);
CREATE UNIQUE INDEX SERVICIO_SVRD_KEY ON SERVICIO_SVRD(OP_GRUPO,SVR_ID);

DROP TABLE IF EXISTS SERVICIO_SVR;
CREATE TABLE SERVICIO_SVR (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID DECIMAL(3) NOT NULL,
  SVR_VERSION DECIMAL(2) NOT NULL DEFAULT 0,
  SVR_COMMAND varchar(255) NOT NULL,
  OP_GRUPO0 char(6) DEFAULT NULL,
  DIC_ID0 DECIMAL(5) DEFAULT NULL,
  OP_GRUPO1 char(6) DEFAULT NULL,
  DIC_ID1 DECIMAL(5) DEFAULT NULL
)
;
CREATE UNIQUE INDEX SERVICIO_SVR_KEY ON SERVICIO_SVR(OP_GRUPO,SVR_ID,SVR_VERSION);

DROP TABLE IF EXISTS SVR_ROL;
CREATE TABLE SVR_ROL (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID DECIMAL(3) NOT NULL,
  ROL_ID DECIMAL(9)  NOT NULL
)
;
CREATE UNIQUE INDEX SVR_ROL_KEY ON SVR_ROL(OP_GRUPO,SVR_ID,ROL_ID);
