DROP TABLE IF EXISTS TEST_UUID;
DROP TABLE IF EXISTS TEST_TEST;
DROP TABLE IF EXISTS TEST_SEQ;
CREATE TABLE TEST_UUID (
  ID CHAR(32) NOT NULL
);

CREATE TABLE TEST_TEST (
  TEST_ID DECIMAL(5) NOT NULL
);

CREATE TABLE TEST_SEQ (
  TEST_ID DECIMAL(5) NOT NULL
);
CREATE UNIQUE INDEX TEST_UUID_KEY ON TEST_UUID(ID);
CREATE UNIQUE INDEX TEST_TEST_KEY ON TEST_TEST(TEST_ID);

