DROP TABLE IF EXISTS DICDESC_DICD;
CREATE TABLE DICDESC_DICD (
  DICD_ID CHAR(32) NOT NULL,
  DICD_DESC text,
  PRIMARY KEY (DICD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS OPERATIVAS_OP;
CREATE TABLE OPERATIVAS_OP (
  OP_GRUPO char(6) NOT NULL,
  DICD_ID CHAR(32),
  OP_DESC varchar(255) DEFAULT NULL,
  PRIMARY KEY (OP_GRUPO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DICCIONARIO_DIC;
CREATE TABLE DICCIONARIO_DIC (
  OP_GRUPO char(6) NOT NULL,
  DIC_ID int(5) unsigned zerofill NOT NULL,
  DIC_TIPO int(1) unsigned zerofill DEFAULT NULL,
  DICD_ID CHAR(32),
  DIC_NOMBRE varchar(50) NOT NULL,
  DIC_LONG0 int(10) unsigned zerofill DEFAULT NULL,
  DIC_LONG1 int(10) unsigned zerofill DEFAULT NULL,
  DIC_STR0 varchar(50) DEFAULT NULL,
  DIC_STR1 varchar(50) DEFAULT NULL,
  DIC_STR2 varchar(50) DEFAULT NULL,
  DIC_STR3 varchar(50) DEFAULT NULL,
  DIC_STR4 varchar(50) DEFAULT NULL,
  DIC_STR5 varchar(50) DEFAULT NULL,
  PRIMARY KEY (OP_GRUPO,DIC_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS REGISTRO_REG;
CREATE TABLE REGISTRO_REG (
  OP_GRUPO char(6) NOT NULL DEFAULT '',
  DIC_ID int(5) unsigned zerofill NOT NULL,
  REG_ORDEN int(3) unsigned zerofill NOT NULL,
  OP_GRUPO0 char(6) NOT NULL,
  DIC_ID0 int(5) unsigned zerofill NOT NULL,
  REG_OBLIGATORIO int(1) unsigned zerofill DEFAULT NULL,
  REG_INT0 int(3) unsigned zerofill DEFAULT NULL,
  REG_INT1 int(3) unsigned zerofill DEFAULT NULL,
  PRIMARY KEY (OP_GRUPO,DIC_ID,REG_ORDEN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SERVICIO_SVRD;
CREATE TABLE SERVICIO_SVRD (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID int(3) unsigned zerofill NOT NULL,
  SVR_VERSION int(2) unsigned zerofill DEFAULT NULL,
  DICD_ID CHAR(32),
  SVR_INHERIT INT(1) UNSIGNED ZEROFILL DEFAULT 1,
  SVR_PUBLIC INT(1) UNSIGNED ZEROFILL DEFAULT 1,
  SVRD_DESC varchar(255) DEFAULT NULL,
  PRIMARY KEY (OP_GRUPO,SVR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SERVICIO_SVR;
CREATE TABLE SERVICIO_SVR (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID int(3) unsigned zerofill NOT NULL,
  SVR_VERSION int(2) unsigned zerofill NOT NULL DEFAULT '00',
  SVR_COMMAND varchar(255) NOT NULL,
  OP_GRUPO0 char(6) DEFAULT NULL,
  DIC_ID0 int(5) unsigned zerofill DEFAULT NULL,
  OP_GRUPO1 char(6) DEFAULT NULL,
  DIC_ID1 int(5) unsigned zerofill DEFAULT NULL,
  PRIMARY KEY (OP_GRUPO,SVR_ID,SVR_VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS SVR_ROL;
CREATE TABLE SVR_ROL (
  OP_GRUPO char(6) NOT NULL,
  SVR_ID int(3) unsigned zerofill NOT NULL,
  ROL_ID int(9) unsigned zerofill  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
