DROP TABLE IF EXISTS TEST_UUID;
DROP TABLE IF EXISTS TEST_TEST;
DROP TABLE IF EXISTS TEST_SEQ;
CREATE TABLE TEST_UUID (
  ID CHAR(32) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TEST_TEST (
  TEST_ID INT(5) unsigned zerofill NOT NULL,
  PRIMARY KEY (TEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TEST_SEQ (
  TEST_ID INT(5) unsigned zerofill NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

